### ISSUE TITLE
How do we deploy the project?

### ISSUE THREAD

**Issue by ziedHamdi** [ManuelDeLeon/sveltekit-firebase-ssr#14]
Thank you for this project, it is nice from you to share your work.

I think there should be a documentation explaining how to deploy the app.

It's not clear to me from the code how the svelte adapter-auto can build both client and server versions. In addition there's Vercel mentioned, so is there a Vercel deployment too? 

From what I've read, we need to put functions in Firebase under the **functions** folder. How come you can use sveltekit `+server.js` files? 

It would be nice from you to explain this a little bit.

**Comment by ManuelDeLeon** [comment]
I'm sorry but that is outside the scope of this project. Please refer to SvelteKit's documentation on deployments and adapters, and if you're planning to deploy to Vercel then check their documentation (although deploying SvelteKit to Vercel is only a matter of pointing to your repo). As for using Firebase functions, I don't think you can do that from a SvelteKit project (like you can do with NextJS + Vercel edge). `+server.js` simply means the REST endpoints will run on the server.
