### ISSUE TITLE
Deploying to node server breaks auth

### ISSUE THREAD

**Issue by ErraticFox** [ManuelDeLeon/sveltekit-firebase-ssr#15]
If I use the `@sveltejs/adapter-node` and then deploy that on a basic express server, authentication seems to work (I can open the Google provider and select my account) but nothing seems to happen on the website, compared to the vercel example. Why is this?

**Comment by ManuelDeLeon** [comment]
Dunno =/ 
If you resolve the issue let's add it to the readme.

**Comment by ErraticFox** [comment]
I switched to Vercel and it seems to be working, but like this [issue](https://github.com/ManuelDeLeon/sveltekit-firebase-ssr/issues/12) (with no answer on how they fixed it), I need to refresh in order to see the auth state (even on localhost). I have a simple profile page using slugs and a way for the user to edit their username and it works perfectly fine and saves to Firestore. I have to be overlooking something or just simply not understanding a specific point. Would you be able to take a look at my project and see if there's anything out of the ordinary whenever you get a chance? As this seems to be the only problem now I'm facing. Repo https://github.com/ErraticFox/chatrr

**Comment by ErraticFox** [comment]
I'm not quite sure what it was, but I rebuilt the app starting with the sveltekit skeleton and that seemed to work even though I don't know what's different. So I'm going to close this now.
