### ISSUE TITLE
Possible to update with tests?

### ISSUE THREAD

**Issue by kirkbushell** [ManuelDeLeon/sveltekit-firebase-ssr#17]
Firstly, thank you very much for this - I was about to setup my own when I found this skeleton app.

It's also given me some insights into how to better organise my configuration - I like the approach you've taken here.

However, writing tests for svelte apps still appears to be an almost entirely black box affair - there's little to no documentation on the official site, and most the examples I've seen appear to be trying to piece together various parts, only to struggle in other areas.

Would be great to update this package with the tests also an example for those of us trying to use best practises for large apps :)

**Comment by ManuelDeLeon** [comment]
That would be outside the scope of this project.
