### ISSUE TITLE
Would you accept a PR for emulator support?

### ISSUE THREAD

**Issue by kirkbushell** [ManuelDeLeon/sveltekit-firebase-ssr#18]
Using the Google firebase console isn't always ideal, and it's nice to be able to test all your features without having to setup a project.

I've made considerable changes to the project in my own, in order to support emulator requirements. Is this something you'd be open to supporting if I open a PR to do similar on this example project?

**Comment by ManuelDeLeon** [comment]
A bit late but sure, if you send a PR with changes to make it work with emulators I'd be happy to accept it. If you do, please make it as simple and clear as possible to get it up and running.

**Comment by ManuelDeLeon** [comment]
Added the emulator
