### ISSUE TITLE
Setting up firestore 

### ISSUE THREAD

**Issue by nalonix** [ManuelDeLeon/sveltekit-firebase-ssr#20]
It's not fetching the user data, userCountData and the session data are undefined.

**Comment by vhollo** [comment]
To fix the Counter, in src/routes/+page.ts change
	let userCountData = parentData.userSession ? await getUserCountData(fetch) : undefined;
to
	let userCountData = parentData.userSession ? await getUserCountData(fetch) : 0;

Very nice example anyway!

**Comment by ManuelDeLeon** [comment]
Check out the latest changes. It's simpler.
