### ISSUE TITLE
Error: Cannot set session store before subscribing

### ISSUE THREAD

**Issue by ErraticFox** [ManuelDeLeon/sveltekit-firebase-ssr#4]
Hello, I'm not quite sure if I missed something somewhere while implementing this, though I keep getting a error saying `Error: Cannot set session store before subscribing` pertaining to this line [here](https://github.com/ManuelDeLeon/sveltekit-firebase-ssr/blob/main/src/lib/utils/firebase.ts#L59). I Googled this with much to no luck. What would be causing this error?

**Comment by ManuelDeLeon** [comment]
When does it happen? Make sure you have latest code and npm update.

**Comment by ErraticFox** [comment]
> When does it happen? Make sure you have latest code and npm update.

I was looking at the code on GitHub, I didn't download it. Also, I linked the script file and line in my last comment on where it happens.

**Comment by ErraticFox** [comment]
Ah my bad, I had added `auth.svelte` but forgot to add the contents to the file 😅

**Comment by ErraticFox** [comment]
I'm convinced I bungled something up when closing it. Because I cannot get it to work ever since shortly after closing this and a couple refreshes.

**Comment by ErraticFox** [comment]
> Does it work on a fresh new clone of this repo?

Yes it does work, but I'm trying to figure out what's the part that makes it work so I can use that knowledge for future projects. 

I remember I saw something on StackOverflow about assigning the session to a variable, like you're doing (explained [here](https://stackoverflow.com/questions/59145105/how-to-write-into-session-store-during-preload))

Though, currently my project is pretty bare right now. For my index my module script: 
```
<script lang="ts" context="module">
    import { browser } from "$app/env";
    import { initializeFirebase, signInWith } from "../lib/client/firebase";
    export async function load({ url, session }: any) {

        const thisSession: any = session;

        if (browser) {
			initializeFirebase(thisSession.firebaseClientConfig);
        }
        return {}
    }
</script>
```
and my firebase script is [here ](https://gist.github.com/ErraticFox/e1845c9a04a7bed3b320e4d578ecdff9)(a teeny bit longer with mostly the basic functions you have created)

Though I'm at a complete loss.

**Comment by ErraticFox** [comment]
Ah, finally! It's been off and on testing the last couple days, but I overlooked the assignment of the session in the non-module script tag.

**Comment by ManuelDeLeon** [comment]
Cool. Glad to hear.
