### ISSUE TITLE
Firebase Server Config?

### ISSUE THREAD

**Issue by nickhibbits** [ManuelDeLeon/sveltekit-firebase-ssr#5]
Hello!

Been working through your repo to better understand auth token management and realtime updates. 

While configuring my local repo I ran into trouble finding the values to add to the "VITE_FIREBASE_SERVER_CONFIG" env variable. This originally came from an error at "decodeToken", from inside api/data.ts.

Where can I find the values you noted in that config in my own Firebase Project?

**Comment by ManuelDeLeon** [comment]
Good question. I updated the readme with the following:

To obtain the necessary server credentials, log in to the Firebase console, click the ⚙️(settings icon), then select `Project Settings` and then the `Service accounts` tab. In the `Firebase Admin SDK` click `Generate new private key`.

These credentials contain a private key that should be kept secret (i.e. not shared or committed to Git)
