### ISSUE TITLE
When navigating directly to a protected route (or when refreshing on a protected route), user is redirected root, even when there is an authenticated user

### ISSUE THREAD

**Issue by nicelion** [ManuelDeLeon/sveltekit-firebase-ssr#8]
When first entering the application, the user is presented `/`, which is a public page as defined in `/lib/utils/constants.ts`

Once a user authenticates, they are then able to access other routes which are not public. However, if an authenticated user attempts to refresh the page on a protected route or attempts to navigate to a protected route via the address bar, the application redirects the user to `/`. 

I have noticed this issue only when running locally. This does not seem to be an issue when I have examined this functionality on the vercel deployment as listed in the README.

**Comment by ManuelDeLeon** [comment]
Pretty sure it's a local issue (don't have it on my end or the live example). Try with the latest code from scratch.
